title: James McKay
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_type: boxed
style: classic
palette: blue
mode: light
base_font: serif
header:
  title: James McKay
  has_primary_nav: true
  primary_nav_links:
    - label: FAQ
      url: /faq
      style: link
    - label: About
      url: /about
      style: link
    - label: Contact me
      url: /contact
      style: link
  has_secondary_nav: false
  has_anncmnt: false
footer:
  has_primary_nav: true
  primary_nav_links:
    - label: About
      url: /about
      style: link
    - label: FAQ
      url: /faq
      style: link
    - label: Contact me
      url: /contact
      style: link
  has_secondary_nav: true
  secondary_nav_links:
    - label: Style Guide
      url: /style-guide
      style: link
    - label: Terms & Conditions
      url: /terms-conditions
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  has_social: true
  social_links:
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/jmckay958/'
      style: link
      has_icon: true
      icon: linkedin
      icon_position: center
      new_window: true
  content: Find me on linked in
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://jamesmckay-personal-a7bb4.netlify.app'
